/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";

export default {
    content: ["./src/**/*.{html,js}"],
    theme: {
        extend: {},
    },
    plugins: [daisyui],
    daisyui: {
        themes: [
            "cupcake",
            "dark",
            "light",
            "business",
            "synthwave",
            "fantasy",
            "corporate",
            "luxury",
            "night",
            "retro",
            "cyberpunk",
            "valentine",
            "garden",
            "dracula",
            "forest",
            "black",
            "lofi",
            "pastel",
            "lemonade",
            "night",
            "emerald",
            "aqua",
            "coffee",
            "bumblebee",
            "cmyk",
            "wireframe",
            "sunset",
            "aqua",
            "coffee",
            "bumblebee",
            "cmyk",
            "wireframe",
            "sunset",
            "aqua",
            "coffee",
            "bumblebee",
            "cmyk",
            "wireframe",
            "sunset",
        ],
    },
};
